name: Build Page

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    container: cypress/browsers:node14.7.0-chrome84

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install root dependencies
      uses: bahmutov/npm-install@v1

    - name: Check if the page builds
      run: npm run-script build
